import { Row } from "./row.interface";

export interface Liquidlabs {
    sqlcount?: string[],
    "Liquidware Labs": string,
    timestamp_now: Date,
    query_id: string,
    inspector: string,
    inspector_id: 0,
    inspector_name: string,
    last_cid_date: Date,
    basis: string,
    simple_basis: string,
    basis_columns: string,
    where_zoom: string,
    bread_crumbs: string,
    by?: string,
    resolution: string,
    report_date: string,
    time_res: string,
    start_date_db: Date,
    end_date_db: Date,
    timezone_hub: string,
    start_date: Date,
    end_date: Date,
    start_time: string,
    end_time: string,
    time_used: string,
    duration: string,
    from_rollups: string,
    use_more_sql: string,
    return_size: string,
    return_count: string,
    limit: string,
    page: string,
    pagination: string,
    total_rows: string,
    columns: string,
    validated_by: string,
    ip_address: string,
    ip_match: string,
    output: string,
    sort_used: string,
    basis_list: string,
    table: Row[]
}
